drop role  A_SC_TEMP_TEMP_2_DBA;
drop role  A_SC_TEMP_TEMP_2_ELT;
drop role  A_SC_TEMP_TEMP_2_ANALYST;

drop role  f_sc_TEMP_TEMP_2_r;
drop role  f_sc_TEMP_TEMP_2_rw;
drop role  f_sc_TEMP_TEMP_2_adm;

-- USE ROLE ACCOUNTADMIN;
-- CREATE OR REPLACE DATABASE TEMP;
-- CREATE OR REPLACE SCHEMA TEMP.TEMP;
-- CREATE OR REPLACE SCHEMA TEMP.TEMP_2;

USE ROLE USERADMIN;

CREATE or replace ROLE A_SC_TEMP_TEMP_2_DBA;
CREATE or replace  ROLE A_SC_TEMP_TEMP_2_ELT;
CREATE or replace  ROLE A_SC_TEMP_TEMP_2_ANALYST;

--access_role
CREATE or replace  ROLE f_sc_TEMP_TEMP_2_r;
CREATE or replace  ROLE f_sc_TEMP_TEMP_2_rw;
CREATE or replace  ROLE f_sc_TEMP_TEMP_2_adm;

grant role A_SC_TEMP_TEMP_2_DBA to role sysadmin;
grant role A_SC_TEMP_TEMP_2_ELT to role sysadmin;
grant role A_SC_TEMP_TEMP_2_ANALYST to role sysadmin;
---------------------------------------------------------------
-- 기능 Role 생성
---------------------------------------------------------------
// F_SC_TEMP_TEMP_2_ADM Role 생성: MY_DB DB 관련된 모든 권한 부여
USE ROLE SECURITYADMIN;

/* 모든 권한을 ro, rw, adm로 나눔 */
---------------------------------------------------------------
-- 기능(prefix : F)은 Role 생성
-- 1. 가장 상위 F_SC_TEMP_TEMP_2_ADM
-- 2. 중위 F_SC_TEMP_TEMP_2_RW
-- 3. 하위 F_SC_TEMP_TEMP_2_R
---------------------------------------------------------------

// 1. F_SC_TEMP_TEMP_2_ADM 에 대한 권한 부여 (아래 건으로 대체됨)
   
/* GRANT OWNERSHIP ON SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_ADM; */
GRANT ALL PRIVILEGES ON SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_ADM;
GRANT ALL ON SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_ADM;

GRANT CREATE TABLE,
   CREATE VIEW,
   CREATE FILE FORMAT,
   CREATE STAGE,
   CREATE PIPE,
   CREATE TASK,
   CREATE SEQUENCE,
   CREATE FUNCTION,
   CREATE PROCEDURE ON SCHEMA TEMP.TEMP_2 
TO ROLE F_SC_TEMP_TEMP_2_ADM;

GRANT ALL ON FUTURE tables in SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_ADM;
GRANT ALL ON FUTURE views in SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_ADM;
GRANT ALL ON FUTURE file formats in SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_ADM;
GRANT ALL ON FUTURE stages in SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_ADM;
GRANT ALL ON FUTURE pipes in SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_ADM;
GRANT ALL ON FUTURE sequences in SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_ADM;
GRANT ALL ON FUTURE functions in SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_ADM;
GRANT ALL ON FUTURE procedures in SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_ADM;
GRANT ALL ON FUTURE tasks in SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_ADM;


// 2. F_SC_TEMP_TEMP_2_RW Role 생성: MY_DB 테이블 INSERT, UPDATE, DELETE 권한 부여 (table, view)
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_RW;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_RW;

GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL views IN SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_RW;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE views IN SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_RW;

USE ROLE SECURITYADMIN;
// 3. F_SC_TEMP_TEMP_2_R 생성: MY_DB 테이블, 뷰 SELECT 권한 부여, 그 외 INTEGRATION STORAGE, STAGE, FILE FORMAT, 특정 WAREHOUSE USAGE 권한 부여
GRANT SELECT ON ALL TABLES IN SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_R;
GRANT SELECT ON ALL VIEWS IN SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_R;

GRANT SELECT ON FUTURE TABLES IN SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_R;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_R;

// 4.공통

--warehouse 등록
-- GRANT USAGE ON INTEGRATION hallym_s3_int TO ROLE F_SC_TEMP_TEMP_2_R;
GRANT USAGE ON ALL STAGES IN SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_R;
GRANT USAGE ON ALL FILE FORMATS IN SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_R;

GRANT USAGE ON FUTURE STAGES IN SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_R;
GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_R;

-- GRANT USAGE ON WAREHOUSE XS_WH TO ROLE F_SC_TEMP_TEMP_2_R;
-- GRANT USAGE ON WAREHOUSE S_WH TO ROLE F_SC_TEMP_TEMP_2_R;
-- GRANT USAGE ON WAREHOUSE M_WH TO ROLE F_SC_TEMP_TEMP_2_R;
-- GRANT USAGE ON WAREHOUSE L_WH TO ROLE F_SC_TEMP_TEMP_2_R;

/*상위 DB에 대한 */
GRANT USAGE ON database TEMP TO ROLE F_SC_TEMP_TEMP_2_R;
GRANT USAGE ON SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_R;

GRANT USAGE ON database TEMP TO ROLE F_SC_TEMP_TEMP_2_RW;
GRANT USAGE ON SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_RW;

GRANT USAGE ON database TEMP TO ROLE F_SC_TEMP_TEMP_2_ADM;
GRANT USAGE ON SCHEMA TEMP.TEMP_2 TO ROLE F_SC_TEMP_TEMP_2_ADM;

/*필요에 따라 판단*/



---------------------------------------------------------------
-- Role 간 관계 설정
---------------------------------------------------------------
USE ROLE SECURITYADMIN;

GRANT ROLE F_SC_TEMP_TEMP_2_R TO ROLE F_SC_TEMP_TEMP_2_RW;
GRANT ROLE F_SC_TEMP_TEMP_2_RW TO ROLE F_SC_TEMP_TEMP_2_ADM;

GRANT ROLE F_SC_TEMP_TEMP_2_R TO ROLE A_SC_TEMP_TEMP_2_ANALYST;
GRANT ROLE F_SC_TEMP_TEMP_2_RW TO ROLE A_SC_TEMP_TEMP_2_ELT;
GRANT ROLE F_SC_TEMP_TEMP_2_ADM TO ROLE A_SC_TEMP_TEMP_2_DBA;

GRANT ROLE A_SC_TEMP_TEMP_2_ANALYST TO ROLE A_SC_TEMP_TEMP_2_ELT;
GRANT ROLE A_SC_TEMP_TEMP_2_ELT TO ROLE A_SC_TEMP_TEMP_2_DBA;

--GRANT ROLE A_SC_TEMP_TEMP_2_ANALYST TO ROLE A_SC_TEMP_TEMP_2_DBA; -- OPTIONAL
GRANT ROLE A_SC_TEMP_TEMP_2_DBA TO ROLE SYSADMIN;
